In [ ]:
"""
넘파이(배열)과 파이썬(리스트) 차이
파이썬 리스트는 큰 메모리, 느린 속도
배열은 빠르고 메모리 할당이 더 적음
동일한 크기의 기억장소가 나열된 것임 즉 배열은 모든 자료형이 동일
데이터의 개수를 변경할 수 없음
파이썬에서는 배열이 없는 이유로 잘 안쓰이기 때문임. 추가로 리스트가 그 역할을 하기도 함.
따라서 파이썬에서 배열을 기본적으로 제공하지 않으므로, 별도로 넘파이 패키지를 설치하여 배열 사용
"""

In [ ]:
# 행렬? 벡터?
"""
벡터 : 숫자를 원소로 갖는 리스트(혹은 배열), 행벡터, 열벡터
행벡터 => x = [x1, x2, ...., xn]
열벡터 => x = [
                [x1],
                [x2],
                ...,
                [xn]
                ]
공간에서의 한 점을 벡터라고 함.
또는 원점으로부터 떨어진 상대적 위치라고도 할 수 있음.
벡터에 -를 곱하면 방향이 반대로 가게 됨
즉 벡터는 과학으로 따졌을 땐 힘(스칼라)과 방향을 의미하므로
방향도 내포되는 표현이기도 함
추가로 많은 양의 데이터를 간결하게 표현하는 방법이기도 함

행렬은 사각형으로 표현하는 것임
행렬: 벡터를 원소로 갖는 2차원 배열
공간에서는 여러개의 점
행렬 곱셈을 통해 벡터를 다른 차원으로 공간을 이동할 수 있음
가로는 행, 세로는 열이라고 부름
"""

In [9]:
li = [1,'가',True, [1,2], {'a':1}]

In [21]:
x = [10,20,30]
type(x) # 리스트

list

In [27]:
import numpy as np
arr = np.array(x) # 1차원 배열(벡터)
print(type(arr)) # 이게 배열임
print(arr)

<class 'numpy.ndarray'>
[10 20 30]


In [ ]:
# 과일가게 장부 관리
# 사과:1000, 딸기:2000, 배: 2000, 파인애플:5000, 바나나:3000
# 5/1 사과:5, 딸기:2, 바나나:3
# 5/2 파인애플:3, 딸기:3, 배:2, 사과:1
# 이러면 그 날의 음식 판매 개수를 일일히 계산을 해야되므로 매출액을 확인하기 어려움
# 이에 따라 판매품목에 종류에 맞춰서 연산하기 시작
# 5/1 사과:5, 딸기:2, 배:0, 파인애플:0, 바나나:3
# 5/2 사과:1, 딸기:3, 배:2, 파인애플:3, 바나나:0
# 위와 같이 만듦. 위를 벡터로 표기하면
# [[5,2,0,0,3],
# [1,3,2,3,0]]
# 위는 5차원 공간임(사과, 딸기, 배, 파인애플, 바나나)
# 5차원 공간에 표현된 한 점
# 점하나는 0차원(스칼라)
# 점이 여러개 모이면 1차원(선)
# 선과 선이 만나서 모이면 2차원(면)
# 면과 면이 만나서 모이면 3차원(입체적 모양)
# 공간과 공간이 모이면 4차원(??)

# 넘파이에서 배열 연산은 C언어로 구현된 반복구조를 사용함.
# 그러므로 일반적인 파이썬의 연산보다 속도가 빠름

# 1차원 배열(벡터)
# 좌표계로 표시할 때(?) x위에 화살표도 같이 표시하는데 이것이 벡터를 의미함

In [24]:
[1,2,3,4,5] * [1,  =  [1, 
               2,     4, 
               3,     9, 
               4,     16, 
               5]     25]
# 위와 같은 행렬의 계산을 적용해서 결과가 나옴

[5,2,0,0,3] + [1,3,2,3,0] = [6, 5, 2, 3, 3]

[5, 2, 0, 0, 3, 1, 3, 2, 3, 0]

In [58]:
# for와 numpy의 속도 비교
import time
data = list(range(1,100000000))
ans = []

In [59]:
start = time.time()
for d in data:
    ans.append(d*2)
end = time.time()
print(end-start)

9.255799293518066


In [40]:
arr_data = np.array(data)
arr_data

array([       1,        2,        3, ..., 99999997, 99999998, 99999999])

In [57]:
start = time.time()
ans2 = 2 * arr_data
end = time.time()
print(end-start)
# for문과 numpy의 단순 연산에서 약 50배의 속도 차이가 생김ㄷㄷ. 
# 근데 1억의 계산이기 때문에 이렇고 규모가 커질수록 격차가 심해짐

0.1442112922668457


In [60]:
x = [1,2]
y = [3,4]
x + y # 파이썬의 연산

[1, 2, 3, 4]

In [62]:
np.array(x) + np.array(y) # numpy의 연산

array([4, 6])

In [ ]:
# 벡터로 만든 이유가 숫자 하나하나가 요소이기 때문
# 간단한 문제
# 1~100까지 수 중에서 짝수를 even, 홀수를 odd에 저장한 다음 같은 위치의 요소끼리 비교하여 큰 값을 출력
# 단, for문을 이용해서
nums = list(range(1,101))
even = []
odd = []
[odd.append(i) if i % 2 == 1 else even.append(i) for i in nums]
for i in range(len(even)):
    print(even[i]) if even[i] > odd[i] else print(odd[i])
        

In [89]:
even=[e for e in range(2,101,2)]
odd=[o for o in range(1,101,2)]
a_even = np.array(even)
a_odd = np.array(odd)
a_even + a_odd

array([  3,   7,  11,  15,  19,  23,  27,  31,  35,  39,  43,  47,  51,
        55,  59,  63,  67,  71,  75,  79,  83,  87,  91,  95,  99, 103,
       107, 111, 115, 119, 123, 127, 131, 135, 139, 143, 147, 151, 155,
       159, 163, 167, 171, 175, 179, 183, 187, 191, 195, 199])

In [92]:
print(a_even > 50)
print(a_even == 50)
print((a_even > 50) & (a_even%5 == 0))
print(a_even)
print(a_odd)
print(a_even>a_odd)
print(a_even[a_even>a_odd])

[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True  True]
[False False False False False False False False False False False False
 False False False False False False False False False False False False
  True False False False False False False False False False False False
 False False False False False False False False False False False False
 False False]
[False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False  True False False False False  True False
 False False False  True False False False False  True False False False
 False  True]
[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40 

In [ ]:
# 위처럼 넘파이를 사용하는 주된 이유는 빠르기 때문임
# 파이썬의 리스트의 경우 데이터가 저장될 때 띄엄띄엄 저장됨
# 넘파이의 배열은 연속되는 저장을 진행하므로 탐색을 할 필요가 없게 됨. 
# 더구나 더 효율적인 C언어로 구동하는 방식이므로 훨씬 빠름
# 그래서 최적화된 연산을 진행할 수 있음
# 넘파이는 대부분 C언어로 구성됨

In [93]:
np.__version__

'1.23.5'

In [102]:
np.array((10,20,30)) # tuple도 배열화 가능
# 0차원 배열 = 스칼라 = 배열의 각 요소값
arr = np.array(10)
arr

array(10)

In [101]:
# 1차원 배열 = 0차원 배열을 요소로 갖는 배열
arr = np.array([10,20,30])
arr

array([10, 20, 30])

In [104]:
# 2차원 배열 = 1차원 배열을 요소로 갖는 배열 = 행렬
arr = np.array([[10,20,30], [100,200,300]])
print(len(arr)) # 행의 개수
print(len(arr[0])) # 열의 개수
arr # 2행 3열

2
3


array([[ 10,  20,  30],
       [100, 200, 300]])

In [113]:
# 3차원(다차원 or n차원) 배열 = 2차원 배열을 요소로 갖는 배열
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr.ndim) # 몇차원인지 확인 가능
print(len(arr)) # ndim-1차원 배열의 개수
arr

2
3


array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

In [117]:
# 아래는 리스트임;;
lst = list(range(1,25))
res = []
for i in range(1,3):
    arr1 = []
    for j in range(1,4):
        arr2 = []
        for k in range(1,5):
            arr2.append(lst[0])
            del lst[0]
        arr1.append(arr2)
    res.append(arr1)
res

[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
 [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]

In [124]:
np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]],
[[13,14,15],[16,17,18],[19,20,21],[22,23,24]]])

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]]])

In [123]:
arr = np.array([[[i for i in range(1,5)],[i for i in range(5,9)],[i for i in range(9,13)]],[[i for i in range(13,17)], [i for i in range(17,21)], [i for i in range(21,25)]]])
arr

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [125]:
#1~24 요소값으로 2*3*4 3차원 배열 생성

ar=np.array([[[ 1, 2, 3, 4],[ 5, 6, 7, 8],[ 9, 10, 11, 12]], 
         [[ 13, 14, 15, 16 ],[17, 18 ,19, 20 ],[21 ,22, 23, 24]]])

In [126]:
li=[[[ 1, 2, 3, 4],[ 5, 6, 7, 8],[ 9, 10, 11, 12]], 
         [[ 13, 14, 15, 16 ],[17, 18 ,19, 20 ],[21 ,22, 23, 24]]]

In [134]:
arr = np.array(list(range(1,25)))
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [143]:
arr_re = arr.reshape(2,3,4) # 행렬 개수, 행 수, 열 수
print(arr_re.shape)
print(arr_re.ndim)
arr_re

(2, 3, 4)
3


array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [162]:
arr = np.array([1,2,3,4])
arr[0]
arr[2]+arr[3]
arr[-1]

4

In [163]:
arr = np.array([list(range(11,16)), list(range(16,21))])
arr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [173]:
arr = np.array(list(range(11,21))).reshape(2,5)
arr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [174]:
arr[1]

array([16, 17, 18, 19, 20])

In [182]:
arr[1][3]
arr[1,3] # 이것도 가능함;; 위와 같은 결과로 확인이 가능
arr[-1][-2]
arr[-1,-2] # 리스트와 동일하게 작동됨

19

In [215]:
arr = np.array(list(range(1,13))).reshape(2,2,3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [216]:
# 그냥해봄
# arr[0,:,2]
arr[0,1,2]

6

In [186]:
# 대기업에서도 딥러닝 수업할 땐 이틀동안 배열만 다룬다고 함
# 데이터 사이언스 직군에서는 넘파이를 사용해야됨. 그리고 주로 사용하도록 만들어 놓음
# 인공지능은 일반적인 IT 직군이 아니므로 넘파이와 판다스를 잘 다루는지를 보게 됨

In [ ]:
# array indexing
# array slicing  영역을 잡고 추출할 때 => arr[시작:끝:간격]

In [217]:
arr=np.array(list(range(1,8)))
arr[1:5] # 리스트와 동일하게 [시작위치 포함, 끝위치 불포함]
arr[3:]
arr[:3]

array([1, 2, 3])

In [ ]:
# 데이터를 가지고 오면 처음에 배열 상태로 가져오므로 배열상태로 다룰 수 있어야 빠른 작업이 가능함

In [218]:
arr[-3:]
arr[-5:-2]
arr[:-3]

array([1, 2, 3, 4, 5, 6, 7])

In [212]:
# 그냥 해봄
# arr1 = np.array(arr,dtype=str)
# arr1

In [224]:
arr[:]
arr[::]
arr[::1]

array([1, 2, 3, 4, 5, 6, 7])

In [226]:
# 우리가 다루는 데이터는 주로 2차원 배열이므로 2차원 슬라이싱을 잘 다뤄야 함.
# 리스트는 느리므로 넘파이의 배열을 사용하는 것임. 우리는 빅데이터를 공부하는 것이므로 연산이 빠르게 가야함
# 파이썬에는 리스트밖에 없는데 이는 빅데이터를 다루지 않기 때문임

In [227]:
arr = np.array(list(range(1,11))).reshape(2,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [228]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [230]:
arr[1,1]
arr[1,1:4]

array([7, 8, 9])

In [232]:
arr = np.array(list(range(11,41))).reshape(6,5)
arr

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40]])

In [239]:
# 34를 참조하기
arr[4,3]
# 21, 22, 23 을 추출
arr[2,:3]
# 17, 18, 19
# 22, 23, 24 를 추출
arr[1:3,1:4] # 넘파이는 각 인덱스에 대해 범위 지정이 가능해짐
arr[1:3][1:4] # 이건 다른 결과가 나옴

array([[17, 18, 19],
       [22, 23, 24]])

In [246]:
arr[1:3][1:4] # 이렇게하면 분리해서 계산을 시도함
arr[1:3]
# 위 결과는 아래인데
# array([[16, 17, 18, 19, 20],
#        [21, 22, 23, 24, 25]])
# 결과에서 [1:4]까지의 행을 다시 찾으니 결과가  [21, 22, 23, 24, 25]로 출력됨
# 즉 결과로는 아래로 나옴
arr[2]
# 이는 문법 문제가 아닌 논리적 오류라고 할 수 있음

array([21, 22, 23, 24, 25])

In [248]:
# 금융 라이브러리
# https://finance.yahoo.com/
!pip install -U finance-datareader


[notice] A new release of pip is available: 23.0.1 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip



     ---------------------------------------- 0.0/46.6 kB ? eta -:--:--
     ---------------------------------------- 46.6/46.6 kB 2.3 MB/s eta 0:00:00


In [ ]:
# https://finance.yahoo.com/
# 위 주소에서 kakao를 검색
# 좌측 메뉴에 Historical Data 클릭 후 다운로드 클릭
# 그럼 035720.KS.csv 파일이 다운로드됨


In [29]:
import pandas as pd
df = pd.read_csv('kakao.csv')
df['Open']

0      58000.0
1      57200.0
2      57500.0
3      57800.0
4      57100.0
        ...   
241    47850.0
242    47650.0
243    48350.0
244    48150.0
245    49000.0
Name: Open, Length: 246, dtype: float64

In [26]:
import numpy as np
# np.loadtxt('kakao.csv') # 이렇게 하면 에러가 나옴= 첫번째 행이 문자열인데 읽으려고 해서 안됨
# np.loadtxt('kakao.csv', skiprows=1, dtype=np.float32, delimiter=',') # 이렇게 하면 날짜 타입을 변환할 수 없다고 함.
# 첫번째 열을 제거해야 읽어올 수 있음. 그러므로 새로 파일을 읽어옴
kakao_arr = np.loadtxt('kakao_pre.csv', skiprows=1, dtype=np.float32, delimiter=',')
print(kakao_arr.shape)
kakao_arr[:5]
kakao_arr[:,2]

(246, 6)


array([57800., 56000., 57100., 57300., 56300., 56000., 55600., 56100.,
       56000., 55600., 56800., 57200., 57600., 57600., 56700., 56300.,
       56400., 56400., 56100., 56000., 56000., 57000., 57300., 56300.,
       56300., 56400., 56200., 55300., 53700., 53400., 52000., 51500.,
       50300., 50100., 49550., 48600., 49350., 48500., 48700., 48400.,
       49300., 49900., 48800., 48700., 49750., 49450., 50000., 50200.,
       51700., 51600., 52200., 51400., 50100., 50100., 49750., 49400.,
       48800., 46650., 47500., 49600., 50000., 51800., 52300., 52300.,
       51000., 51200., 51800., 52100., 51900., 50600., 50600., 49850.,
       49150., 48200., 48250., 48400., 48450., 48900., 47600., 47800.,
       48000., 48750., 48100., 47950., 48400., 48850., 48500., 48600.,
       48000., 47900., 48150., 47300., 47450., 48100., 48450., 47800.,
       47050., 45600., 44800., 44650., 43400., 43150., 41600., 40700.,
       40600., 41200., 41900., 42600., 43050., 42400., 42800., 41800.,
      

In [1]:
import FinanceDataReader as fdr

In [2]:
df_krx = fdr.StockListing('KRX')
type(df_krx)

pandas.core.frame.DataFrame

In [ ]:
df_krx

In [ ]:
# 연습문제

In [30]:
# 1.
# 넘파이를 사용하여 다음과 같은 행렬을 만든다.
# 10 20 30 40
# 50 60 70 80
import numpy as np
nums = np.array(list(range(10,90,10))).reshape(2,4)
nums

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [35]:
# 2.
# 다음 행렬과 같은 행렬이 있다.

# m = np.array([[ 0,  1,  2,  3,  4],
#             [ 5,  6,  7,  8,  9],
#             [10, 11, 12, 13, 14]])
# 이 행렬에서 값 7 을 인덱싱한다.
# 이 행렬에서 값 14 을 인덱싱한다.
# 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
# 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
# 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
m = np.array([[ 0,  1,  2,  3,  4],
            [ 5,  6,  7,  8,  9],
            [10, 11, 12, 13, 14]])
print(m[1,2])
print(m[-1,-1])
print(m[1:,2])
print(m[:2,3:])

7
14
[ 7 12]
[[3 4]
 [8 9]]


In [65]:
# 3. 값이 10에서 49를 원소로 가지고 있는 벡터 만들기
# nums = np.array(list(range(10,50))).reshape(5,8)
nums = np.array(list(range(10,50)))
nums

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [66]:
# 4. 3번 배열의 원소를 뒤집어 출력
print(nums[::-1])

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [69]:
# 5. 삼성전자 주가 데이터 다운로드
# -날짜 열 제거
# -시가, 종가, 고가, 저가, 거래량을 각각 추출
# -2024년 5월 1일~ 5월 3일까지 데이터만 추출
# -슬라이싱, 인덱싱 연습
import pandas as pd
df = pd.read_csv('samsung_electronic.csv')
print(df.tail()) # 24년 5월은 3일까지의 데이터는 2일밖에 없음
df.drop('Date', axis=1, inplace=True)
df.to_csv('ss_electronic_stock.csv', index=False, encoding='utf-8')
ss_stock = np.loadtxt('ss_electronic_stock.csv', skiprows=1, dtype=np.float32, delimiter=',')
ss_stock[-2:]

           Date     Open     High      Low    Close  Adj Close    Volume
241  2024-04-26  77800.0  77900.0  76500.0  76700.0    76700.0  12755629
242  2024-04-29  77400.0  77600.0  76200.0  76700.0    76700.0  14664474
243  2024-04-30  77000.0  78500.0  76600.0  77500.0    77500.0  19007007
244  2024-05-02  77600.0  78600.0  77300.0  78000.0    78000.0  18900640
245  2024-05-03  79000.0  79000.0  77500.0  77700.0    77700.0  11957343


array([[   77600.,    78600.,    77300.,    78000.,    78000., 18900640.],
       [   79000.,    79000.,    77500.,    77700.,    77700., 11957343.]],
      dtype=float32)