In [1]:
import numpy as np
arr = np.array([1,2,3,4,])
np.flip(arr) # 배열 뒤집기 == arr[::-1]

array([4, 3, 2, 1])

In [13]:
arr2d = np.arange(30).reshape(6,5)
arr2d[::-1]

array([[25, 26, 27, 28, 29],
       [20, 21, 22, 23, 24],
       [15, 16, 17, 18, 19],
       [10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4]])

In [31]:
np.flip(arr2d) # arr2d[::-1,::-1]

array([[29, 28, 27, 26, 25],
       [24, 23, 22, 21, 20],
       [19, 18, 17, 16, 15],
       [14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

axis 에러가 나올 때가 있는데 이때는 축을 잘못지정했거나 행 또는 열이 안맞는다는 뜻임

axis(축), axes(모든축), axis=0(행 방향 뒤집기)

In [34]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [47]:
arr2d[:, ::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20],
       [29, 28, 27, 26, 25]])

In [50]:
# array([[ 4,  3,  2,  1,  0],
#        [ 9,  8,  7,  6,  5],
#        [14, 13, 12, 11, 10],
#        [19, 18, 17, 16, 15],
#        [24, 23, 22, 21, 20],
#        [29, 28, 27, 26, 25]]) 배열 만들기
np.flip(arr2d, axis=1)
arr2d[::,::-1]

array([[ 4,  3,  2,  1,  0],
       [ 9,  8,  7,  6,  5],
       [14, 13, 12, 11, 10],
       [19, 18, 17, 16, 15],
       [24, 23, 22, 21, 20],
       [29, 28, 27, 26, 25]])

In [54]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [53]:
arr2d[2:]


array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [66]:
arr1 = np.zeros((3,3))
arr2 = np.ones((3,2))
arr12 = np.hstack([arr1, arr2])
arr3 = np.arange(10,151,10).reshape(3,-1)
arr3
np.tile(np.vstack([arr12, arr3]), (2,1))

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [7]:
arr1 = np.zeros([3])
arr2 = np.ones([2])
arr12 = np.hstack([arr1,arr2])

arr12_tile = np.tile(arr12, (3,1))


In [15]:
arr3 = np.linspace(10,150, 15).reshape(3,-1)
arr123 = np.vstack([arr12_tile, arr3])
res = np.tile(arr123,(2,1))
res

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [ ]:
arr = np.arange(11,21).reshape(2,-1)
arr

In [54]:
# 많이 쓰는 함수
np.sum(arr) # == arr.sum() 이렇게도 사용 가능함...
np.min(arr) # == arr.min()
np.max(arr) # == arr.max()
np.argmin(arr) # 최솟값의 위치
np.argmax(arr) # 최댓값의 위치
arr.mean() # 평균 - 이상치(극단값같은 것들)에 약한 산술구조임

15.5

In [56]:
np.sum(arr) 
np.min(arr)
np.max(arr) # 벡터 형태로 잡혀도 전체 데이터에서 계산을 함.
np.max(arr[0]) # 물론 인덱스를 지정하면 지정된 인덱스의 데이터에 대해서 계산

# 추가로 2차원에 대한 합, 최소값, 최대값 이런식으로 연산을 했는데 이것은 차원 축소 연산임

15

In [48]:
arr[0].argmax() # 9
arr[0].argmin() # 0
test = np.array([0,5,3,4,1])

1

In [62]:
np.median(np.array([1,2,100])) # 중위수를 추출함(홀수개일 때는 중앙값, 짝수일때는 중앙의 2개 평균)
np.median(arr[0])

13.0

In [61]:
# 100만 1000만 100억
np.median(arr)

15.5

In [66]:
np.all(2>1)
np.all([2>1, 5>3])
np.all([2>1, 5>3, 3<1]) # 하나라도 False이면 False를 리턴

False

In [70]:
np.any(1>2)
np.any([1>2,3>2]) # 하나라도 True라면 True 리턴

True

In [74]:
np.all([1,2,3]) # True
np.all([1,2,0]) # False
np.all([1,2,0.1]) # True
# 0이면 거짓, 0이 아니면 참

True

In [77]:
np.all(np.arange(5)) # 0이 포함되어 False
np.all(np.arange(1,5)) # True

True

In [78]:
a = np.zeros(10, dtype=np.int32)
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [79]:
a == 0

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [80]:
np.all(a==0)

True

In [89]:
# 풀어보기
# a에 저장된 값들이 모두 b에 저장된 값보다 작거나 같으면서
# b에 저장된 값들이 모두 c에 저장된 값보다 작거나 같은가?
# True가 나와야 함
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

In [94]:
np.all(b <= c) & np.all(a<=b)
np.all([b<=c, a<=b])
np.all((b<=c) & (a<=b))

True

In [105]:
# 2차원 이상 다차원 배열에 대한 연산시엔 axis를 지정할 수 있음
# axis = 0(기본값?, 열방향 연산), axis=1(행방향 연산)
arr = np.arange(10).reshape(2,5)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [102]:
print(arr.sum(axis=0))
print(arr.sum(axis=1))
print(arr.sum())

[ 5  7  9 11 13]
[10 35]
45


In [104]:
arr.max(axis=0)

array([5, 6, 7, 8, 9])

In [167]:
a = np.array([[4,  3,  5,  7],
              [1, 12, 11,  9],
              [2, 15,  1, 14]])
# a 배열의 각 행 최댓값을 구하라
# a.max(axis=1)
print(a)

[[ 4  3  5  7]
 [ 1 12 11  9]
 [ 2 15  1 14]]


In [166]:
a.sort(axis=1)
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [168]:
a.sort(axis=0)
a

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [159]:
a.sort()
a

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [150]:
np.sort(a) # np.sort(a, axis=1) # 왼쪽에서 오른쪽으로 오름차순

array([[ 3,  4,  5,  7],
       [ 1,  9, 11, 12],
       [ 1,  2, 14, 15]])

In [152]:
np.sort(a, axis=0) # 위에서 아래로 오름차순 정렬

array([[ 1,  3,  1,  7],
       [ 2, 12,  5,  9],
       [ 4, 15, 11, 14]])

In [169]:
arr = np.array([40,20,10,30,90])
arr

array([40, 20, 10, 30, 90])

In [175]:
np.sort(arr) # 정렬. 파이썬에서 sorted() 사용했을 때와 동일함(적용이 안되고 결과 반환만)
np.sort(arr)[::-1]
np.flip(np.sort(arr)) # 바로 위코드와 동일함

array([90, 40, 30, 20, 10])

In [185]:
len(arr)
np.mean(arr)# 평균: 주어진 수의 합을 측정개수로 나눔
np.var(arr) # 분산(모분산): 편차의 제곱의 평균값.(변수의 흩어진 정도) 
# 클수록 데이터가 크게 흩뿌려져 있는 상태, 작을수록 밀집상태인 것=비슷한 데이터
# 분산에 대해서는 아래에서 서술함
np.std(arr) # 표준편차: 분산의 제곱근(**0.5)

27.85677655436824

In [205]:
np.var([1,2]) # 평균값은 1.5, x1 = 1(리스트의 첫번째)-평균값, x2 = 2(두번째)-평균값
                # (0.5**2)=0.25   +(0.5**2)=0.25   = 0.5
            #   0.5/len([1,2]) = 0.25(분산값)
            #  추가로 표본분산이라고 하는 것도 있는데 이 경우는 0.5/(len([1,2]) - 1) 
            # 이렇게 분모를 1깎아서 계산함(모분산에 가깝게 나올 수 있게 한다고 함;)

0.25

<!-- 요약하면 평균을 구해서 데이터마다 평균을 빼고 각 데이터별로 제곱
제곱한 모든 데이터들을 합해서 전체 개수를 나눔 -->
<!-- 표준분산의 경우 전체개수-1을 나누면 됨 -->

In [ ]:
# 5월 기온 데이터가 있다고 가정할때, 데이터의 분산과 우리들의 키에 대한 데이터 분산 중 어느쪽이 더 클까
# 어떤 상태일 때 데이터의 구분이 쉬워질까?(분산클때? 작을때?) 클때가 정답임
# 키가 [160 165 175 190]이렇게 있다면 여기서 평균은 172
# -12 -7 3  18 근데 평균으로부터 떨어진 거리를 봐야함
# (-12)**2, -7**2, 3**2, 18**2 이렇게 값을 전부 양수로 만든 후
# 위의 값을 전부 합한 후 합한 개수(4)를 나눈 값임

In [209]:
# x에 대한 표본분산을 구하시오
x = np.array([5,10,9,3,8])

In [245]:
np.sum((x - np.mean(x))**2)/(len(x)-1) # 표본 분산

8.5

In [248]:
np.var(x) # 모분산
np.var(x, ddof=1) # 표본분산이 됨;;

8.5

In [249]:
x = np.arange(1,201)
x

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [254]:
np.percentile(x,0) # 최소값

1.0

In [256]:
np.percentile(x,100) # 최댓값
# 백분위 수: 위치를 100으로 나눈 수
# 1사분위수 : 25% 백분위

200.0

In [267]:
print(np.percentile(x,0))
print(np.percentile(x,25))
print(np.percentile(x,50))
print(np.percentile(x,75))
print(np.percentile(x,100))

1.0
50.75
100.5
150.25
200.0


In [276]:
data = np.arange(11)
print(np.percentile(data,25)) # 1사분위수
print(np.percentile(data,50)) # 중위수(2사분위수)
print(np.percentile(data,75)) # 3사분위수
print(np.percentile(data,100)) # 4사분위수

2.5
5.0
7.5
10.0


In [ ]:
스크래핑 자동화 + 기능 추가
gpt API를 이용

In [ ]:
# 프로젝트 주제로 함 알아보기

# 1. 스크래핑 자동화
# 지속적 스크래핑 -> 정제 -> db 테이블 저장 -> 읽기 -> 사용하기(ETL)
# 카카오톡 api를 이용하여 나만의 톡 분석
# 그냥 gpt API을 이용해서 프로젝트를 진행하는 것이 좋을 거 같기도 함

# 2. 게임(지뢰제거, 슈팅)

# 3. 주문/관리/예약/추천시스템 구현

# 4. 사진 편집 프로그램(포토샵 기능) openCV
# https://076923.github.io/posts/Python-opencv-1/#google_vignette
# 위 주소 참고

# 5. 날씨 등 뉴스 정보 제공 사이트 제작(규모를 크게 하면 파이널 프로젝트로 가야할 것 같음)
# 감성분석사전(재밌다(5), 졸렸다(1), 이게영화냐(0)...)

# 6. 성격 유형 검사 프로그램

# 7. 데이터 전처리 분석 관련 주제
# kaggle.com, aihub.or.kr, dacon.io


# 기간이 짧은만큼 애자일 기법으로 진행하는 것이 좋음


In [277]:
# 이전 기수로는 뇌공학을 전공했는데 뇌분석으로 성향분석을 하는 프로젝트를 했었다고 함
# 우울증 검사같은 것도...

In [ ]:
# 프로젝트 관해서

# 리스트 페이지
# 어떤 언론사의 기사를 스크래핑하나? 
# -> 일단 한군데만 스크래핑 하며 기능 확장시 여러개 혹은 사용자가 지정한 언론사의 사이트 스크래핑하는 것으로...
# 뉴스 기사를 스크래핑해옴 -> 스크래핑하는 시간을 정할 필요가 있을 것
# 뉴스 기사를 검색 -> 특정 키워드만 검색(키워드의 조건이 있어야 될 듯)


# 상세페이지
# 1. 뉴스 기사의 요약본이 작성되어 있음(GPT설명 참조)
# 2. 원문 링크가 있음
# 3. GPT프롬프트


# GPT
# GPT는 API를 이용해서 어떤 말투, 어떤 대화가 오갈지에 대한 사전정보를 제시할 수 있을 것임
# 이에 따라 GPT로 뉴스 기사를 요약해서 데이터를 가져온 것을 바로 GPT에 요약요청하여 요약된 데이터를 DB에 저장
# DB에서 불러와 상세페이지 - 요약본 항목에 출력


# # 역할
# # 장고, 웹 스크래핑, API

In [6]:
# 1.
# 실수로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.

# 전체의 최댓값

# 각 행의 합

# 각 행의 최댓값

# 각 열의 평균

# 각 열의 최솟값

import numpy as np
data = np.arange(30).reshape(5,6)
data

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [18]:
print('전체의 최댓값: ',np.max(data))
print('각 행의 합: ',*np.sum(data, axis=1))
print('각 행의 최댓값: ', *np.max(data, axis=1))
print('각 열의 평균값: ', *np.mean(data, axis=0))
print('각 열의 최솟값: ', *np.min(data, axis=0))

전체의 최댓값:  29
각 행의 합:  15 51 87 123 159
각 행의 최댓값:  5 11 17 23 29
각 열의 평균값:  12.0 13.0 14.0 15.0 16.0 17.0
각 열의 최솟값:  0 1 2 3 4 5


In [87]:
# 2.
# 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 
# 영어 성적을 기준으로 각 열(column)을 재정렬하라.

# array([[  1,    2,    3,    4],
#        [ 46,   99,  100,   71],
#        [ 81,   59,   90,  100]])


score = np.array([[  1,    2,    3,    4],
                [ 46,   99,  100,   71],
                [ 81,   59,   90,  100]])

In [86]:
eng = np.sort(score[1]) # 영어 점수만 정렬
score_t = score.T
eng_score_sort = []
for i, s in enumerate(eng):
    for j in range(len(score_t)):
        if s == score_t[j][1]:
            eng_score_sort.append([j+1, s, score_t[j][2]])
nums = np.array(eng_score_sort)
res = nums.T
res

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])

In [97]:
eng = np.argsort(score[1])
score[:,eng]

array([[  1,   4,   2,   3],
       [ 46,  71,  99, 100],
       [ 81, 100,  59,  90]])