In [2]:
import numpy as np

arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
arr.reshape(12)
arr.reshape(3*4)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [6]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
arr.flatten() # 다차원 배열을 1차원 배열로 변환 = 평탄화 작업이라고 함
arr.ravel() # 풀어내는 작업 = 다차원을 1차원으로... 뭔차이지?

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [28]:
x = np.arange(3) # 1차원 배열
x

array([0, 1, 2])

In [29]:
x.reshape(1,3) # 2차원 배열 (행렬1*3)

array([[0, 1, 2]])

In [30]:
x.reshape(3,1) # 2차원 배열 (행렬3*1)

array([[0],
       [1],
       [2]])

In [34]:
print(x[:,np.newaxis]) # 차원이 증가함
print(x[:,np.newaxis].shape) # shape = (3,1)

[[0]
 [1]
 [2]]
(3, 1)


In [36]:
arr2 = arr.flatten()
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [40]:
for i in arr2:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [38]:
arr3 = arr.reshape(4,3)
arr3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [39]:
for i in arr3:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [41]:
for i in arr3:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [42]:
arr4 = arr.reshape(2,3,2)
arr4

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [46]:
for i in arr4:
    for j in i:
        for k in j:
            print(k)

0
1
2
3
4
5
6
7
8
9
10
11


In [48]:
# 파이썬에서 사용했던 자료구조
# 리스트(list), 튜플(tuple), 딕셔너리(dict), 집합(set), 

# 판다스: 데이터프레임(dataframe), 시리즈(series)
# matplotlib, seaborn, plotly, tableau(다른 소프트웨어 프로그램), ...
# numpy = 데이터를 전처리하기 위한 용도임(빠른 연산)
# 배열(ndarray = n dimension array), 
# 데이터 수집(크롤링, db) -> 전처리(넘파이, 판다스)
# 컬러이미지: 1000, 1000, 3  * 10만장
# [
#     [
#         [200 0 0 255 255 255 0 0 0 ...],    # 행
#         [200 0 0 255 255 255 0 0 0 ...],
#         ...
#         [200 0 0 255 255 255 0 0 0 ...], 
#     ], # 1채널
#     [
#         [200 0 0 255 255 255 0 0 0 ...],
#         [200 0 0 255 255 255 0 0 0 ...],
#         ...
#         [200 0 0 255 255 255 0 0 0 ...], 
#     ],# 2채널
#     [
#         [200 0 0 255 255 255 0 0 0 ...],
#         [200 0 0 255 255 255 0 0 0 ...],
#         ...
#         [200 0 0 255 255 255 0 0 0 ...], 
#     ] # 3채널 
# ],# 이미지 1개
# [...] # 이미지 n개



배열 합치기

In [74]:
a1 = np.ones((2,3))
a2 = np.zeros((2,2))
a3 = np.zeros((3,3))
print('a1', a1)
print('a2', a2)
print('a3', a3)

a1 [[1. 1. 1.]
 [1. 1. 1.]]
a2 [[0. 0.]
 [0. 0.]]
a3 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [81]:
a3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [85]:
np.hstack([a1, a2]) # horizental = 수평 : 행 개수가 같아야 함
np.vstack([a1, a3]) # vertical = 수직 : 열 개수가 같아야 함
np.dstack([a3, a3, a3, a3]) # depth - 깊이 : 행렬이 같아야 함. 합칠수록 열이 늘어나는 것처럼 보이나 열이 아닌 '깊이'가 늘어나는 것임

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [95]:
a1=np.arange(12).reshape(3,4)
a2=np.zeros((3,4))
print(a1.shape)
print(a2.shape)
np.dstack([a1,a2]) # 보면 depth에 해당하는 부분은 뒤에 열로 생겨남
# 보기가 어렵게 되므로 dstack함수는 잘 사용되지 않으며 stack을 주로 사용함

(3, 4)
(3, 4)


array([[[ 0.,  0.],
        [ 1.,  0.],
        [ 2.,  0.],
        [ 3.,  0.]],

       [[ 4.,  0.],
        [ 5.,  0.],
        [ 6.,  0.],
        [ 7.,  0.]],

       [[ 8.,  0.],
        [ 9.,  0.],
        [10.,  0.],
        [11.,  0.]]])

In [97]:
print(np.stack([a1, a2]).shape) # stack을 사용하면 새로 앞에 shape를 추가하므로 보편적으로 바라보는 형태로 차원이 생성됨
np.stack([a1, a2]) # axis(축)를 지정, 기본값은 0

(2, 3, 4)


array([[[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]],

       [[ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.]]])

In [107]:
r1 = np.stack([a1,a2], axis=1) # 순서가 바뀜. axis=2 로 세팅하면 dstack과 동일한 결과 확인 가능
r1

array([[[ 0.,  1.,  2.,  3.],
        [ 0.,  0.,  0.,  0.]],

       [[ 4.,  5.,  6.,  7.],
        [ 0.,  0.,  0.,  0.]],

       [[ 8.,  9., 10., 11.],
        [ 0.,  0.,  0.,  0.]]])

In [108]:
r2 = np.stack([a1,a2], axis=2) 
r2

array([[[ 0.,  0.],
        [ 1.,  0.],
        [ 2.,  0.],
        [ 3.,  0.]],

       [[ 4.,  0.],
        [ 5.,  0.],
        [ 6.,  0.],
        [ 7.,  0.]],

       [[ 8.,  0.],
        [ 9.,  0.],
        [10.,  0.],
        [11.,  0.]]])

In [ ]:
# 두 행렬 (3,4), (3,4)를 stack함수로 연결할 때 axis값에 따라 shape이 달라짐
# axis=0 => 2,3,4
# axis=1 => 3,2,4
# axis=2 => 3,4,2

In [120]:
# 아래와 같은 배열이 있을 때 
a1 = np.array([1,2,3])
a2 = np.array([11,12,13])

# array([ 1,  2,  3, 11, 12, 13]) 만들기
np.hstack([a1,a2])
np.r_[a1,a2] # 위와 같은 결과를 보여줌. 인덱서 함수


# array([[ 1, 11],
#        [ 2, 12],
#        [ 3, 13]])
np.c_[a1,a2]
# np.c_[a1,a2] == np.vstack([a1,a2]).T ( 이런 것도 있구나.. )

array([[ 1, 11],
       [ 2, 12],
       [ 3, 13]])

In [143]:
# tile : 동일한 배열을 반복해서 연결
arr = np.arange(6).reshape(2,3)
print(arr)
print(np.tile(arr, 3)) # 기본값: (n,1)
print(np.tile(arr, (3,1)), end='\n\n') # 상하반복 3회, 좌우반복 1회
print(np.tile(arr, (3,1,1)), end='\n\n')  # 차원을 늘릴수도 있음;;

[[0 1 2]
 [3 4 5]]
[[0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5]]
[[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]

[[[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]

 [[0 1 2]
  [3 4 5]]]



In [157]:
# [0, 0, 0, 1, 1],
# [0, 0, 0, 1, 1],
# [0, 0, 0, 1, 1]] 이와 같은 결과를 만들어라

arr1 = np.array([0,0,0,1,1])
arr2 = np.zeros(3, dtype=np.int8)
arr3 = np.ones(2, dtype=np.int8)
np.tile(np.hstack([arr2,arr3]), (3,1))
# np.tile(arr1, (3,1))

array([[0, 0, 0, 1, 1],
       [0, 0, 0, 1, 1],
       [0, 0, 0, 1, 1]], dtype=int8)

In [199]:
x = np.arange(3)
y = np.arange(5)

In [200]:
x, y = np.meshgrid(x,y)
x

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [195]:
y

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [172]:
# (x,y) = (0,0),(0,1),..,(1,4),..,(2,4)

In [201]:
[list(zip(x,y)) for x,y in zip(x,y)]

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [202]:
[list(zip(x,y)) for x,y in zip(x,y)] # 사각형 만들기...근데 데이터분석하면서 쓸일이 없음(강사님 말씀)..

[[(0, 0), (1, 0), (2, 0)],
 [(0, 1), (1, 1), (2, 1)],
 [(0, 2), (1, 2), (2, 2)],
 [(0, 3), (1, 3), (2, 3)],
 [(0, 4), (1, 4), (2, 4)]]

In [203]:
arr1 = np.arange(1,4)
arr2 = np.arange(11,33,10)

In [206]:
np.concatenate([arr1, arr2]) # 데이터 합치기 
np.concatenate((arr1, arr2)) # 위와 결과 같음

array([ 1,  2,  3, 11, 21, 31])

In [ ]:
arr3 = np.array(np.arange(1,4))
arr4 = np.array(np.arange(11,33,10))

In [219]:
# array([[ 0,  1,  2,  3,  4,  5],
#        [10, 11, 12, 13, 14, 15],
#        [20, 21, 22, 23, 24, 25],
#        [30, 31, 32, 33, 34, 35],
#        [40, 41, 42, 43, 44, 45],
#        [50, 51, 52, 53, 54, 55]]) 이와 같이 만들어 볼 것
# 내 답안
arr1 = np.arange(6)
arr2 = np.arange(0, 51, 10)
n, m = np.meshgrid(arr1, arr2)
m + n

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [230]:
arr1 = np.arange(6)
arr2 = np.arange(0, 56, 10)
arr1 + arr2[:, np.newaxis] # 브로드캐스팅을 이용한 방법임

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [232]:
arr=np.arange(6)
arr_f= [arr + i*10 for i in range(6)]
np.array(arr_f)

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
arr = np.arange(6)
res = arr
for i in range(5):
    new_arr = res + 10
    res = np.vstack([arr, new_arr])
res

In [ ]:
arrays = []
for i in range(6):
    arr = np.arange(0 + i * 10, 6 + i * 10)
    arrays.append(arr)
res = np.concatenate(arrays)
res.reshape(6,6)

벡터화 연산

In [246]:
a = np.arange(1,5) # 1 2 3 4
b = np.array([4,2,2,4])
np.all(a>=b) # 배열 모든 요소가 True여야 True를 반환

False

In [251]:
# 벡터(행렬)끼리 연산하려면 크기가 동일해야함
# 브로드캐스팅: 벡터(행렬)의 크기가 다르더라도 연산이 가능하도록
# 크기를 동일하게 해주는 작업
# 벡터    스칼라
# 1                 11
# 2   +    10   =   12
# 3                 13

# 간단한 예시로
# arr = np.array([1,2,3,4]) + 4
# print(arr)
# 위의 예제가 브로드캐스팅이라고 할 수 있음

In [268]:
# 행렬(2)    벡터(1)
# 0 1 2       10      10 11 12
# 1 2 3   +   11   =  12 13 14
# 2 3 4       12      14 15 16

arr = np.array([np.array([0,1,2]), np.array([1,2,3]), np.array([2,3,4])])
arr2 = np.array([np.array([10]), np.array([11]), np.array([12])])
arr3 = np.array([1,2,3])
arr+arr2
arr+arr3

array([[1, 3, 5],
       [2, 4, 6],
       [3, 5, 7]])

In [265]:
x = np.arange(5)
y = np.ones_like(x) 
x + y # x + y == x + 1

array([1, 2, 3, 4, 5])

In [269]:
arr1 = np.arange(6)
arr2 = np.arange(0,56,10)

array([0, 1, 2, 3, 4, 5])

In [289]:
# array([[0, 1, 2],
#        [1, 2, 3],
#        [2, 3, 4],
#        [3, 4, 5],
#        [4, 5, 6]])
# x = np.arange(3)
# y = np.array([[0],[1],[2],[3],[4]])
# x+y

# np.array([np.array([0+i,1+i, 2+i]) for i in range(5)])   

x = np.arange(3)
y = np.array([np.array([i]) for i in range(5)])
x+y

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [292]:
y = np.arange(5)
y.reshape(5,1)

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [ ]:
x=np.arange(3)
y=np.arange(5)
x,y=np.meshgrid(x,y)
x+y

In [ ]:
arr=np.arange(3)
arr_f= [arr + i for i in range(5)]
arr_f=np.array(arr_f)
arr_f

In [ ]:
x,y=np.meshgrid(np.arange(3),np.arange(5))
x+y

In [ ]:
x = np.arange(3)
y= np.arange(5).reshape(5,1)
x+y

In [298]:
# 강사님 풀이
np.vstack([range(7) [i:i+3] for i in range(5)])

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
# 안성진 노래나 영화 추천
# 김상준 영화흥행예측
# 최신기사를 가져와서 텍스트 요약


In [301]:
# 연습문제

In [ ]:
# 1. 
# 지금까지 공부한 명령어를 사용하여 다음과 같은 배열을 다양한 방법으로 만드시오.
# - tile사용, tile 미사용,...
# array([[   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [   0.,    0.,    0.,    1.,    1.],
#        [  10.,   20.,   30.,   40.,   50.],
#        [  60.,   70.,   80.,   90.,  100.],
#        [ 110.,  120.,  130.,  140.,  150.]])

In [390]:
import numpy as np
arr1 = np.hstack([np.zeros(3), np.ones(2)]) + np.array([0,0,0]).reshape(3,1)
arr2 = np.arange(10, 160, 10).reshape(3,5)
arr3 = np.vstack([arr1,arr2])
np.vstack([arr3,arr3])

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [388]:
arr = np.hstack([np.zeros([3,3]), np.ones([3,2])])
arr2 = np.arange(10, 160, 10).reshape(3,5)
np.vstack([arr, arr2, arr, arr2])

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [387]:
arr0 = np.array([0])
arr1 = np.array([1])
r = np.hstack([arr0,arr0,arr0, arr1,arr1])
rc = np.vstack([r,r,r])
t_arr = np.arange(1,16, dtype=np.float16).reshape(3,5)*10
np.vstack([rc,t_arr,rc,t_arr])

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [399]:
array = np.concatenate([np.zeros(3), np.ones(2)])
array = np.vstack([array, array, array])
array2 = ((np.arange(15)+1)*10).reshape(3,5)
result_array = np.vstack([array, array2, array, array2])
result_array

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [400]:
np.array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

array([[  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [  0.,   0.,   0.,   1.,   1.],
       [ 10.,  20.,  30.,  40.,  50.],
       [ 60.,  70.,  80.,  90., 100.],
       [110., 120., 130., 140., 150.]])

In [441]:
# 2.  아래와 같은 구조의 배열을 생성하시오
# 1 2 3 4 5
# 10 9 8 7 6
# 11 12 13 14 15
# 20 19 18 17 16
# 21 22 23 24 25

arr = np.arange(1,26).reshape(5,5)
for i in range(len(arr)):
    arr[i] = arr[i] if arr[i][0] % 2 == 1 else arr[i][::-1]
print(arr)

[[ 1  2  3  4  5]
 [10  9  8  7  6]
 [11 12 13 14 15]
 [20 19 18 17 16]
 [21 22 23 24 25]]


In [440]:
array = np.array([np.arange(5)+1])
for i in range(4):
    array2 = array[i] + np.arange(9,0,-2) if i % 2 == 0 else array[i] + np.arange(1,10,2)
    array = np.vstack([array, array2])
print(array)

array([[ 1,  2,  3,  4,  5],
       [10,  9,  8,  7,  6],
       [11, 12, 13, 14, 15],
       [20, 19, 18, 17, 16],
       [21, 22, 23, 24, 25]])

In [ ]:
주식 데이터 시각화(주식이 내려갈지 올라갈지?)) - 수업에서 할 것임 그래서 패스
지역에 따른 집값 예측(다양한 변수를 적용하여 집값이 어떻게 변동이 생기는지) - 예측 모델을 만들 것이므로 패스
기후 분석(추후의 기온이나 날씨 등이 어떻게 진행될지) - 우리가 하게 될 주제들임
질병 분석(감기라던지 코로나라던지 어느정도의 위험성을 보이고 감염증상이 생기는지) - 패스
영화 리뷰 분석(평가가 어느쪽으로 치우치는지) - 패스
음악 영화 추천 - 수업에서 배울 것이긴 함...

환경 분석(어떤 환경이 개선되는지 오염되는지)
영화 흥행 분석


강사님은 스크래핑을 자동으로 하는 것이 괜찮을 거 같다고 하심.
예를 들어 뉴스기사를 자동으로 스크래핑하는 프로그램을 만들고 그것을 DB에 저장하는 것까지
텍스트 정제는 못해도 수집 및 저장까지만 해도 괜찮음.
의료 관련 기사라던지 AI관련 타임즈?같은 것도 주기적으로 스크래핑해서 저장한다던지(파이프라인같이 설계해서)
윗 내용에 대해서 고민할 점은 과일 가격 관련해서 이슈가 많아서 
사과 관련 기사를 스크래핑하고 싶으면 '사과'라는 단어는 맥락을 보고 판단을 해야됨

In [ ]:
# 환경분석은 괜찮아보인다고 하심
키워드의 분포 시각화
키워드의 트렌드, 어떤 단어가 많이 언급되었는지
미세먼지같은 단어는 과거에 사용하지 않았음
신문기사가 옛날부터 있는 것들도 있는데
텍스트로 된 기사들을 가지고 하면 어떨지. 근데 텍스트 마이닝을 가지고 해봐야됨

축사, 악취 이슈가 많음