지금의 3개월이 앞으로의 업무를 결정할 수 있을 것임;
근데 gpt가 3년 경력자와 비슷한 개발 실력이 있다고 함...

LLM을 만드는 방법은 배움(직접 만들진 않음)
만들어져 있는 모델로 파인튜닝하는 법은 배울 것
그리고 강사님은 LLM 수업도 하고 계심(정확히는 LLM의 전문가이심)
LLM을 이용해서 문제를 해결하는 능력을 갖춘사람을 기업에서 원함
LLM이 비전이 있음
그리고 LLM보다는 NLP(자연어처리)로 검색하는 것이 더 범위가 넓음

1MB  = 100만 바이트
1GB = 10억 바이트
32GB = 320억 바이트
320억/4 = 80억개 정수를 저장할 수 있음

In [4]:
import numpy as np
# arr = np.array(list(range(10,90,10))).reshape(2,4)
arr = np.array(list(range(1,5))) # 보통은 array를 만들지 않아도 데이터가 있으므로 잘 안사용함
arr.dtype

dtype('int32')

In [11]:
arr = np.array(['APPLE','BANANA','CHERRY'])
arr.dtype # '<U6' => unicode

dtype('<U6')

In [10]:
arr = np.array(['APPLE','BANAN','CHERR'])
arr.dtype # '<U5' => unicode+가장 큰 길이

dtype('<U5')

In [29]:
arr = np.array([1,2,3]) # 32bit
print(arr.dtype) # 통상적인 크기 4바이트

arr = np.array([1,2,3], dtype=np.float32) # 32bit
print(arr.dtype)
arr = np.array([1,2,3], dtype=np.int64) # 16bit
print(arr.dtype)
arr = np.array([1,2,3], dtype=np.int16) # 16bit
print(arr.dtype)
arr = np.array([1,2,3], dtype=np.int8) # 8bit
print(arr.dtype)

# arr = np.array([1,2,3], dtype=np.float128) # int, float 128bit 는 없음


int32
float32
int64
int16
int8


In [40]:
arr = np.array([1,2,3], dtype=np.float32) # 32bit
arr # 실수 타입
# 64비트 float 수의 범위 = 4.9 * 10^(-324) ~ 1.79 * 10^308승 이 범위를 벗어나는 수식을 사용할 일은 현재 없음
# 32비트 float 수의 범위 = 1.4 * 10^(-45) ~ 3.4 * 10^38승

# 32bit in 수의 범위 = -21억 ~ 21억
# 32bit in 수의 범위 = -922경 ~ 922경
# 만약 위의 범위를 벗어나야 하면 다른 방법을 적용해야됨

array([1., 2., 3.], dtype=float32)

In [62]:
arr = np.array([1,2,3, -129], dtype=np.int8) # 8bit : -128~127
arr.dtype
arr # 이러면 범위를 벗어나게 되서 보수연산을 진행하게 됨(2의 보수 연산을 찾으면 됨)

array([  1,   2,   3, 127], dtype=int8)

In [54]:
arr = np.array([1,2,3], dtype='i1') # i바이트수
arr.dtype

array([1, 2, 3], dtype=int8)

In [52]:
arr = np.array([1,2,3]) # 32bit
arr.dtype # mac os는 64, windows는 32비트로 출력됨

dtype('int32')

In [53]:
farr = arr.astype(np.float32) # 타입 변경
farr

array([1., 2., 3.], dtype=float32)

In [72]:
# 파이썬에서는
myList = [1,2,'3']
myList
# 넘파이에서는
my_list = np.array([1,2,'3'])
my_list # 문자열로 변환되어 저장

array(['1', '2', '3'], dtype='<U11')

In [89]:
arr1 = np.array(list(range(10,14))).reshape(2,2)
arr2 = np.array(list(range(10,14))).reshape(2,2)
arr3 = np.array(list(range(10,12)))

In [96]:
print(arr1 - arr2) # 넘파이 배열은 요소간 연산 => 동일한 크기의 배열
print(arr1 * 2)
print(arr1 - arr3) # 개수가 안맞으면 해당하는 행과 열에 대해서만 계산
print(arr1 * arr2) # 주의 : 행렬의 곱셈(matrix multiply => arr1 * 2)이 아님, 요소간 곱셈(element-wise product)이 됨
# 요소간 곱셈으로 arr1 .(dot) arr2 이렇게 계산함


[[0 0]
 [0 0]]
[[20 22]
 [24 26]]
[[0 0]
 [2 2]]
[[100 121]
 [144 169]]


In [94]:
# 2x1 . 1x3 = 2x3 (True)
# 3x2 . 2x2 = 3x2 (True)

[[100 121]
 [144 169]]


In [98]:
arr1 = np.array(list(range(10,14))).reshape(2,2)
arr2 = np.array(list(range(13,17))).reshape(2,2)

In [105]:
arr1 > arr2
arr1 > 10 # 요소간 비교
~(arr1 == arr2) # ~는 not 연산자
arr1 != arr2 # != 같지 않다

array([[ True,  True],
       [ True,  True]])

In [107]:
(~(arr1 == arr2) | (~(arr1!= arr2)))
#  행렬         OR      행렬   => 요소간 OR 연산

array([[ True,  True],
       [ True,  True]])

In [111]:
np.arange(10) # np.array(list(range(10)))
np.arange(8).reshape(4,2)
np.arange(8).reshape(2,2,2)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [114]:
# 1~24까지의 값, 2*3*4 행렬 생성해보기
np.arange(1,25).reshape(2,3,4)
np.array(range(1,25)).reshape(2,3,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]])

In [128]:
data = np.arange(200)
print(data.shape)

data2 = data.reshape(4,-1) # -1은 알아서 만들라는 의미
print(data2.shape)
# data2

data3 = data.reshape(-1, 8) # 행이든 열이든 한쪽은 -1로 입력할 수 있음
print(data3.shape)

data.reshape(-1,5, 10) # 4,5,10
data.reshape(4,-1, 10)

(200,)
(4, 50)
(25, 8)


array([[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
        [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
        [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
        [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49]],

       [[ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
        [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
        [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
        [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
        [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

       [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
        [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
        [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
        [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
        [140, 141, 142, 143, 144, 145, 146, 147, 148, 149]],

       [[150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
        [160, 161, 162, 163, 164, 

In [132]:
# data3 = data.reshape(6,-1) 이와 같은 경우 에러가 출력됨 = 200의 약수에 6이 포함되지 않기 때문임
# 10부터 시작하여 2스텝으로 증가, 3행 4열
np.arange(10, 34, 2).reshape(3,-1)

array([[10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [137]:
# boolean 참조(팬시참조) 자주 쓰임
arr = np.array([1,2,3,4])
idx = np.array([True, False, False, True])
arr[idx] # true에 해당하는 index값만 남겨서 출력. 단 길이가 같아야 가능함
# 위와 같은 것이 boolean참조

array([1, 4])

In [150]:
np.min(arr)
np.max(arr)

4

In [148]:
(arr == np.min(arr)) | (arr == np.max(arr))

array([ True, False, False,  True])

In [151]:
arr[(arr == np.min(arr)) | (arr == np.max(arr))] # 이런 사용법이 흔함

array([1, 4])

In [144]:
lst = [1,2,3,4]
for i in lst:
    if(i == 1):
        print(i)
# 위의 코드가 아래로 쉽게 작성 가능함
arr[arr == 1] # true에 해당하는 값만 출력할 수 있음
# res = arr > 2
# arr[res]

array([1])

In [181]:
# 11부터 20까지의 수가 저장된 배열 arr을 생성하시오
arr = np.arange(11,21)
# arr[arr % 2 == 0]

In [176]:
# 12, 14를 추출하고 싶을 때
# arr[1, 3] # 이렇게 하면 error!
arr[np.array([1,3])]
arr[np.array([1,3,5,7,9])]
# 또는
arr[[1,3]]
# 속도면에서는 np.array()로 입력하는 것이 대규모일 때 훨씬 빠를 것임

array([12, 14])

In [179]:
# arr = array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
idx = np.array([0,0,0,1,1,1,3,3,3])
arr[idx]

array([11, 11, 11, 12, 12, 12, 14, 14, 14])

In [204]:
arr = np.arange(10,40).reshape(5,-1)
arr[:] # 전체 행 추출
arr[:, :] # 전체 행에 대해 전체 열 추출
arr[:,[True,True,True,False,False,False]]

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26],
       [28, 30, 32],
       [34, 36, 38]])

In [197]:
arr[:,idx]

array([[10, 10, 10, 11, 11, 11, 13, 13, 13],
       [16, 16, 16, 17, 17, 17, 19, 19, 19],
       [22, 22, 22, 23, 23, 23, 25, 25, 25],
       [28, 28, 28, 29, 29, 29, 31, 31, 31],
       [34, 34, 34, 35, 35, 35, 37, 37, 37]])

In [211]:
# arr에서 1(10~), 3(12~), 5(14~) 번째 열을 출력
arr[:,[0,2,4]] # 가장 많이 쓰이는 문법
arr[:,[True, False, True, False, True, False]]
arr[:, np.arange(0,5,2)]
arr[:, np.array([0,2,4])]
# 위는 전부 동일한 결과를 보임

array([[10, 12, 14],
       [16, 18, 20],
       [22, 24, 26],
       [28, 30, 32],
       [34, 36, 38]])

In [213]:
arr[:,[4,1,3,0]] # 순서를 바꿔서 얻을 수도 있음

array([[14, 11, 13, 10],
       [20, 17, 19, 16],
       [26, 23, 25, 22],
       [32, 29, 31, 28],
       [38, 35, 37, 34]])

In [215]:
arr

array([[10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39]])

In [217]:
# arr 에서 3번째 2번째 4번째 행 순서로 데이터 추출하기
arr[[2,1,3]]

array([[22, 23, 24, 25, 26, 27],
       [16, 17, 18, 19, 20, 21],
       [28, 29, 30, 31, 32, 33]])

In [361]:
# 무한대(infinity) : np.inf
np.array([1]) / np.array([0]) # 
np.log(0)
# 즉 과정이 잘못됐을 때 나오기 쉬움
# 숫자가아님(not a number): np.nan
np.array([0]) / np.array([0]) # 0/0


C:\Users\fkfma\AppData\Local\Temp\ipykernel_15408\1325775961.py:2: RuntimeWarning: divide by zero encountered in divide
  np.array([1]) / np.array([0]) #
C:\Users\fkfma\AppData\Local\Temp\ipykernel_15408\1325775961.py:3: RuntimeWarning: divide by zero encountered in log
  np.log(0)
C:\Users\fkfma\AppData\Local\Temp\ipykernel_15408\1325775961.py:6: RuntimeWarning: invalid value encountered in divide
  np.array([0]) / np.array([0]) #


array([nan])

In [379]:
np.zeros(3) # 0으로 채워진 배열 생성
np.ones((3,2)) # 1로 채워진 3x2배열 생성
np.zeros((3,2), dtype='i') # i = int32, i1 = int8
arr = np.ones((3,2))*2 # 곱하여 생성하는 것이 가능하므로 np.zeros와 np.ones만 있음
arr # ???근데 *0 을 적용하면 똑같이 0이 되지 않나? => 0이 많이 쓰이기 때문에 따로 만든 거라고 보긴 함

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [383]:
# np.ones_like가 np.ones나 np.zeros보다 더 잘 쓰임. 구조를 복사하기 때문
# arr
# array([[2., 2.],
#        [2., 2.],
#        [2., 2.]])
np.ones_like(arr) # 아래가 결과
# array([[1., 1.],
#        [1., 1.],
#        [1., 1.]])


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [385]:
np.arange(2,31,2).reshape(-1, 3)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24],
       [26, 28, 30]])

In [389]:
# np.linspace(시작할 숫자, 마치막 숫자, 총 데이터 개수)
np.linspace(0,10,5) # 선형회귀인가?

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [395]:
arr = np.arange(1,7).reshape(2,3)
arr.transpose() # 행과 열을 변경 => 2행3열 - 3행2열
# arr.transpose().transpose() # 원상복구
arr.T # transpose()와 동일함

array([[1, 4],
       [2, 5],
       [3, 6]])

In [404]:
# 사과, 배, 딸기
data = np.array([[1,5,0],
                [5,3,2],
                [1,2,0]])
price = np.array([[1000], [5000], [8000]])
data.shape # 3행 3열
price.shape # 3행 1열
# data배열과 price배열간에 행렬의 곱셈 연산이 가능한가? => 가능함
print(data.dot(price)) # 벡터의 내적
print(data@price) # 행렬 연산의 경우 dot == @
# CNN할 때 많이 보게 될 것..

[[26000]
 [36000]
 [11000]]
[[26000]
 [36000]
 [11000]]


In [419]:
# soft copy
arr = np.arange(10,15) # array([10, 11, 12, 13, 14])
arr2 = arr # 데이터 공유('뷰'라고도 함)
arr2[1] = 99
print(arr2)
print(arr)

[10 99 12 13 14]
[10 99 12 13 14]


In [418]:
# deepcopy
arr = np.arange(10,15) # array([10, 11, 12, 13, 14])
arr3 = arr.copy() # 데이터를 복사 array([10, 11, 12, 13, 14])
arr3[1] = 99
print(arr3)
print(arr)

[10 99 12 13 14]
[10 11 12 13 14]


In [357]:
# 뜬금없는데 np에 랜덤도 있음;;

1

In [ ]:
# 연습문제


In [2]:
# 1. 1차원 numpy 배열을 만들어 결과와 같이 출력하기
# [ 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]

import numpy as np
np.arange(0,30,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [424]:
# 2. 2차원 numpy 배열을 만들어 결과와 같이 출력하기
# [[10, 20, 30, 40],
# 50, 60, 70, 80]]

np.arange(10,90,10).reshape(2,4)

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [475]:
# 3. 3차원 numpy 배열을 만들어 결과와 같이 출력하기
# [[[ 1, 2, 3],
# [ 4, 5, 6]],
# [[ 7, 8, 9],
# [10, 11, 12]],
# [[13, 14, 15],
# [16, 17, 18]],
# [[19, 20, 21],
# [22, 23, 24]]]

np.arange(1,25).reshape(-1,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24]]])

In [429]:
# 4. 아래와 같은 행렬을 이용하여 조건에 맞는 코드 작성
# vector = np.array(range(0, 30, 2))

# 값 24 인덱싱
#  값 6 인덱싱

vector = np.array(range(0, 30, 2))
print(vector[-3])
print(vector[3])

24
6


In [436]:
# 5. 아래와 같은 행렬을 이용하여 조건에 맞는 코드 작성
# matrix = np.array([
# [1, 2, 3, 4],
# [5, 6, 7, 8],
# [9, 10, 11, 12],
# [13, 14, 15, 16]
# ])

# - 값 8 인덱싱
# - 값 2 인덱싱
# - 값 9 인덱싱
# - 값 15 인덱싱

matrix = np.array([
[1, 2, 3, 4],
[5, 6, 7, 8],
[9, 10, 11, 12],
[13, 14, 15, 16]
])
print(*matrix[matrix == 8])
print(matrix[0,1])
print(matrix[2][0])
print(matrix[-1,-2])

8
2
9
15


In [437]:
# 6. 아래와 같은 행렬을 작성해보세요
# [-1, -2, -3, -4, -5]
np.array([-1, -2, -3, -4, -5])

array([-1, -2, -3, -4, -5])

In [9]:
# 7.
# 다음 행렬과 같은 배열이 있다.

# x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
#              11, 12, 13, 14, 15, 16, 17, 18, 19, 20])
# 이 배열에서 3의 배수를 찾아라.
# 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
# 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.

x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
             11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

print(x[x%3 == 0])
data = x[x%4==1]
print(data)
idx = x[x%4==1] % 3 == 0
print(data[idx])
print(x[(x%3==0) & (x%4==1)])


[ 3  6  9 12 15 18]
[ 1  5  9 13 17]
[9]
[9]


In [8]:
x[(x%3==0) & (x%4==1)]

array([9])

In [474]:
# 8. 다음 배열을 만들고 슬라이싱, 인덱싱 연습하세요
# arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
# arr2d
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d, end='\n\n')
print(arr2d[:,2], end='\n\n')
print(arr2d[:,2:], end='\n\n')
print(arr2d[1:,:], end='\n\n')
print(arr2d[1,1], end='\n\n')
print(arr2d*2, end='\n\n')


arr2d_2 = np.array([[1], [4], [7]])
print(arr2d+arr2d, end='\n\n')
print(arr2d*arr2d_2, end='\n\n')
print(arr2d_2.T)
arr2d_structure = np.ones_like(arr2d)
print(arr2d_structure)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[3 6 9]

[[3]
 [6]
 [9]]

[[4 5 6]
 [7 8 9]]

5

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

[[ 1  2  3]
 [16 20 24]
 [49 56 63]]

[[1 4 7]]


array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])