In [ ]:
감성분석: 감성사전
1-gram(유니그램)
2-gram(???)
       
영어는 nltk 패키지
한국어 konlpy
http://api.openhangul.com/overview?m=sentiment

In [43]:
import numpy as np
np.random.seed(20240510)
np.random.rand(10)


array([0.24432338, 0.63551756, 0.67221731, 0.8370985 , 0.3230404 ,
       0.66728613, 0.99852928, 0.95145872, 0.36059922, 0.68687786])

In [70]:
x = np.arange(10)
print(x)
np.random.shuffle(x) # 변수에 바로 적용됨
print(x)

[0 1 2 3 4 5 6 7 8 9]
[2 5 6 4 7 9 3 1 0 8]


In [88]:
# choice : 표본 추출 함수
np.random.choice(x,2) # (배열, 추출 개수)


array([5, 4])

In [128]:
# np.random.rand() : 0<= 난수<1
np.random.randn() #: 평균은 0에 근접, 표준편차는 1에 수렴하는 데이터를 추출
np.mean(np.random.randn(10)) # 평균
np.std(np.random.randn(10)) # 표준편차
np.random.randint(2) # 입력된 값이 자연수라면 미만의 0과 자연수를 추출
# '[0, 5)'개구간이라고 하는데 '[0' 은 0을 포함, '5)'라고 하면 5미만 이라는 의미가 됨
np.random.randint(2,4)
np.random.randint(2,4, size=10) # size는 추출할 개수를 의미함
np.random.randint(2,4, size=(2,5)) # 튜플형식으로 입력하여 배열을 만들어 추출할 수도 있음

array([[2, 2, 3, 3, 2],
       [2, 3, 3, 2, 3]])

In [130]:
data = np.random.randint(5,11, size=10)

In [131]:
data

array([ 9,  6, 10,  8, 10,  5,  7,  5,  7, 10])

In [133]:
np.unique(data) # set과 같은 효과를 보여주나 집합 형태가 아닌 배열 형태로 반환

array([ 5,  6,  7,  8,  9, 10])

In [134]:
np.unique(data, return_counts=True) # 각 데이터별로 빈도가 어떻게 되는지를 같이 출력해줌

(array([ 5,  6,  7,  8,  9, 10]), array([2, 1, 2, 1, 1, 3], dtype=int64))

In [138]:
np.unique(data, return_counts=True)[0]
np.unique(data, return_counts=True)[1]

array([2, 1, 2, 1, 1, 3], dtype=int64)

In [142]:
np.bincount(data, minlength=12) # 0부터 시작하여 가장 큰 수까지 데이터의 빈도를 출력함.
# minlength를 입력하면 최소 출력개수를 지정할 수 있음
# minlength가 11이면 0부터 10까지(총11개) 빈도수를 추출할 수 있음
#결과 : array([0, 0, 0, 0, 0, 3, 0, 1, 2, 1, 3], dtype=int64)
            # 0  1  2  3  4  5  6  7  8  9  10

array([0, 0, 0, 0, 0, 2, 1, 2, 1, 1, 3, 0], dtype=int64)

In [196]:
# 로또 수 5개 출력
for i in range(5):
    print(np.random.randint(1,46, size=6))
# 동전 10번 던져 앞뒷면 가상 실험
print(np.random.randint(2, size=10))
# 주사위 109번 던져 나온 숫자 평균
print(np.mean(np.random.randint(1,7, 100)))

[ 7 27 20 25 11 10]
[ 1  8 17 36 22 31]
[10 40  4 16 11 16]
[ 8 18 18 27 22  1]
[37 13  1 25 13  5]
[0 0 1 0 1 1 1 1 0 1]
3.4


In [192]:
# 4시부터 프로젝트 초안 발표 및 질의응답 
# = 질문 및 가능한지 문제점 등을 설명할 것임(5~10분)

# - 프로젝트 팀명, 팀 구성원
# - 목표(목적), 일정, 예상 산출물 개요
# - 사용 기술(툴), 구현 방법, 데이터 출처
# - 향후 개선 방향(일정)
# 5시부터 평가시험

3.34

In [ ]:
# 오후 5시 ~ 평가
# 오후 4시 ~ 프로젝트 발표 및 질의응답(5분~10분)
# -프로젝트 팀명, 팀 구성원(역할), 
# -목표(목적), 일정, 예상 산출물 개요
# -사용 기술(툴), 구현 방법, 데이터 출처
# -향후 개선 방향(일정)
# 1시 30분부터 3시 50분까지 회의후 플젝 설명

In [ ]:
# 스크래핑을 한곳에서 할 것인데, 그날 나온 스크래핑, 스크래핑출력 시 화면에 사진도 나와야 함

# 스크래핑 데이터가 큰지 작은지에 따라 요약한 글자 수를 조절해야될 것 같음

# 키워드

In [ ]:
# 장고 페이지에서 게시글 보는 것은 아무나 볼 수 있으나 세팅을 저장하기 위해서는 저장하고 보는 것이 좋음

# 로그인시 혜택 = 이건 나중에 개선사항으로 남겨두는 것으로...
# - 키워드 검색, 요약 분량, 알림?(지정한 키워드의 뉴스가 나왔을 때 플로팅?)