In [ ]:
# python, numpy, pandas
# 통계분석
# 데이터마이닝
# 시각화(matplotlib, tableau, seaborn, plotly,...)

# 머신러닝(scikit-learn)
# 딥러닝(tensorflow, keras, pytorch) - cnn, rnn(lstm), rl, yolo 등

In [2]:
# 6월 24일부터 파이널 프로젝트를 진행할 것이라고 하심

In [3]:
import numpy as np
np.random.seed(12345)

In [4]:
np.set_printoptions(precision=4) # 반올림(기본값은 8자리로 설정됨), 자릿수 지정

In [5]:
np.array([1.23456789])

array([1.2346])

In [6]:
np.set_printoptions(precision=8) 
np.array([1.23456789])


array([1.23456789])

In [7]:
np.array([1.2345678951651616544561132151])

array([1.2345679])

In [15]:
np.arange(2000) # 1000까지 전체 출력, 1000개 초과시 ...으로 중략

array([   0,    1,    2, ..., 1997, 1998, 1999])

In [18]:
np.set_printoptions(threshold=1500) # 출력 갯수 조절
np.set_printoptions(threshold=np.inf) # 무한하게 출력
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [83]:
data = [np.random.standard_normal() for _ in range(7)] # 평균이 0이며 표준편차가 1인 값(근접한 값으로 출력함)
print(data)
sum(data)

[-1.9462303856987244, 0.5050317838715824, -0.9104891380445155, -0.21969628544760295, 0.4080553829055946, -0.6031454111648193, -0.36113259447515733]


-3.127606648053642

In [84]:
a = [1,2,3]
b = a # 얕은 복사
a == b

True

In [85]:
c = a.copy()
c

[1, 2, 3]

In [86]:
a[1] = 4
print(c, b) # 깊은 복사와 얕은 복사의 차이

[1, 2, 3] [1, 4, 3]


In [88]:
c = '''
This is a longer string that
spans multiple lines
'''
c.count('\n') # 줄바꿈 개수 체크

3

In [89]:
a = 'this is a string'
b = a.replace('string', 'longer string')
b

'this is a longer string'

In [91]:
a = 5.6
print(str(a))

5.6


In [93]:
s = '12\\34'
print(s) # 역슬래시는 두번 사용해야 한번 출력된다는 뜻

12\34


In [95]:
a = 'this is the first half'
b = ' and this is the second half'
a+b

'this is the first half and this is the second half'

In [101]:
template = '{0:.2f} {1:s} are are worth US ${2:d}'
template.format(88.46, 'ArgentinePesos', 1)

'88.46 ArgentinePesos are are worth US $1'

In [103]:
amount = 10
rate = 88.46
currency = 'Pesos'
result = f"{amount} {currency} is worth US${amount/rate}"
result

'10 Pesos is worth US$0.11304544426859599'

In [104]:
False or True

True

In [105]:
from datetime import datetime, date, time
dt = datetime(2024, 5, 21, 9, 45, 21)
dt

datetime.datetime(2024, 5, 21, 9, 45, 21)

In [108]:
print(dt.day)
print(dt.minute)
print(dt.date())
print(dt.time())

21
45
2024-05-21
09:45:21


In [109]:
states = ["   Alabama ", "Georgia!", "Georgia", "georgia", "FlOrIda",
          "south   carolina##", "West virginia?"]

In [116]:
import re
def clean_strings(strings):
    result = []
    for value in strings:
        value = value.strip()
        value = re.sub('[!#?]', '', value)
        value = value.title() # 첫글자를 대문자로 변환
        result.append(value)
    return result

In [117]:
clean_strings(states)

['Alabama',
 'Georgia',
 'Georgia',
 'Georgia',
 'Florida',
 'South   Carolina',
 'West Virginia']

In [122]:
arr1 = np.array([1,2,3], dtype=np.float64) # float64비트로 설정
int_arr1 = arr1.astype(np.int32) # int32비트로 타입 변경
int_arr1

array([1, 2, 3])

In [123]:
arr = np.array([[1,2,3],[4,5,6]])
arr * arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [124]:
arr2 = np.array([[0,4,1], [7,2,12]])
arr2>arr

array([[False,  True, False],
       [ True, False,  True]])

In [127]:
arr = np.arange(10)
print(arr[5:8])
arr[5:8] = 12
arr

[5 6 7]


array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [128]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [130]:
arr_slice[1] = 12345
arr # 얕은 복사이므로 복사본이 변경되더라도 원본도 변경됨

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [133]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[2, 1]

8

In [131]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [136]:
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.array([[4, 7], [0, 2], [-5, 6], [0, 0], [1, 2],
                 [-12, -4], [3, 4]])
print(names == 'Bob')
print(names[names == 'Bob'])

[ True False False  True False False False]
['Bob' 'Bob']


In [138]:
data[names == 'Bob'] # names안에 Bob이 있으면 False True를 반환하므로 같은 배열의 결과를 참고하여 추출을 할 수 있음

array([[4, 7],
       [0, 0]])

In [139]:
data[names == 'Bob', 1] # data[names == 'Bob'] 이 결과의 1번째 열을 추출하는 것임

array([7, 0])

In [142]:
names != 'Bob'
# !(names == 'Bob) 이건 문법적 오류임

array([False,  True,  True, False,  True,  True,  True])

In [143]:
~(names == 'Bob') # 이것이 name != 'Bob'과 같은 결과를 출력함

array([False,  True,  True, False,  True,  True,  True])

In [144]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [145]:
data

array([[  4,   7],
       [  0,   2],
       [ -5,   6],
       [  0,   0],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [147]:
# names가 Bob이 아닌 사람들에 대한 data배열의 값을 출력
data[names != 'Bob']

array([[  0,   2],
       [ -5,   6],
       [  1,   2],
       [-12,  -4],
       [  3,   4]])

In [166]:
data[(names == 'Bob') | (names == 'Will')] # bob과 will이 있는 데이터만 출력

array([[ 4,  7],
       [-5,  6],
       [ 0,  0],
       [ 1,  2]])

In [170]:
print(data[data < 0])
data<0

[ -5 -12  -4]


array([[False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [ True,  True],
       [False, False]])

In [ ]:
# names에서 이름이 Joe가 아닌 사람들에 대한 data 요소 값을 모두 7로 변경
data[names != 'Joe'] = 7

In [171]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [174]:
arr[[4,3,6,0]] # 인덱싱 안에 대괄호를 씌우면 순서를 바꿔서 뽑아낼 수 있음. [행, 열]에서 행을 배열로 한 것으로 취급

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [6., 6., 6., 6.],
       [0., 0., 0., 0.]])

In [177]:
arr[[-1,-5,-3],1:3]

array([[7., 7.],
       [3., 3.],
       [5., 5.]])

In [227]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [213]:
# 행 인덱스 1,5,7,2번 행 추출
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [215]:
# 행 인덱스 1,5,7,2번 행 및 0,3,1,2 열 순으로 추출
arr[[1,5,7,2],[0,3,1,2]]
arr1 = arr[:,[0,3,1,2]]
arr1[[1,5,7,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [222]:
arr[:,[0,3,1,2]][[1,5,7,2]] #arr 배열에서 열의 순서 지정하여 추출후 행 추출
arr[[1,5,7,2]][:,[0,3,1,2]] #arr 배열에서 행 추출후 열의 순서 지정하여 추출

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [229]:
arr[[1,5,7,2],[0,3,1,2]] = 0
arr

array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

In [230]:
arr[[1,5,7,2]] = 0
arr

array([[ 0,  1,  2,  3],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [ 0,  0,  0,  0],
       [24, 25, 26, 27],
       [ 0,  0,  0,  0]])

In [232]:
arr = np.arange(15).reshape(3,5)
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [233]:
arr = np.array([[0, 1, 0], [1, 2, -2], [6, 3, 2], [-1, 0, -1], [1, 0, 1]])
arr

array([[ 0,  1,  0],
       [ 1,  2, -2],
       [ 6,  3,  2],
       [-1,  0, -1],
       [ 1,  0,  1]])

In [237]:
arr @ arr.T # @ == 애트라고 말함. 5행3열 @ 3행 5열 => 5행 5열
arr.T @ arr # 3행 5열 @ 5행 3열 => 3행 3열

array([[39, 20, 12],
       [20, 14,  2],
       [12,  2, 10]])

In [238]:
arr = np.arange(10)
np.sqrt(arr) # 제곱근 구하기

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [239]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])

In [247]:
xarr[cond],yarr[~cond]

(array([1.1, 1.3, 1.4]), array([2.2, 2.5]))

array([1.1, 1.2, 1.3, 1.4, 1.5])

In [277]:
a = [(x, y, z) for x,y,z in zip(xarr, yarr, cond)]
[i[0] if i[2] == True else i[1] for i in a]
# [x if z else y for x,y,z in zip(xarr, yarr, cond)] 이게 더 쉬움

[1.1, 2.2, 1.3, 1.4, 2.5]

In [279]:
# 위와 같은 결과
np.where(cond, xarr, yarr)
xarr[cond] = yarr[cond]
xarr
# np.where(조건, 참, 거짓)


array([1.1, 1.2, 1.3, 1.4, 1.5])

In [300]:
arr = np.random.standard_normal([4,4])
arr>0

array([[False, False, False,  True],
       [False,  True, False,  True],
       [ True, False, False, False],
       [False,  True,  True,  True]])

In [301]:
np.where(arr>0, 1,-1)

array([[-1, -1, -1,  1],
       [-1,  1, -1,  1],
       [ 1, -1, -1, -1],
       [-1,  1,  1,  1]])

In [302]:
arr = np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [304]:
# arr에서 3의 배수는 3출력, 아니면 원래 값을 출력
np.where(arr%3==0, 3, arr)

array([[ 3,  1,  2,  3],
       [ 4,  5,  3,  7],
       [ 8,  3, 10, 11]])

In [309]:
np.mean(arr) # 평균
np.mean(arr, axis=1) # 행의 평균
np.mean(arr, axis=0) # 열의 평균

array([4., 5., 6., 7.])

In [311]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr.cumsum() # 누적하여 합산한 결과를 보여줌

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [324]:
arr = np.random.standard_normal(100)
(arr>00).sum() # true: 1, false: 0

48

In [326]:
bools = np.array([False, False, True, False])
bools.sum() # 1출력
bools.any() # True 출력
bools.all() # 전부 True 여야 True

False

In [329]:
arr2 = np.array([5,-10, 7, 1, 0, -3])
np.sort(arr2) # 이 시점만 정렬됨
arr2

array([  5, -10,   7,   1,   0,  -3])

In [331]:
names = np.array(["Bob", "Will", "Joe", "Bob", "Will", "Joe", "Joe"])
np.unique(names) # 중복 제거

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [332]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

In [335]:
# 위와 동일한 결과를 보여줌
set(names)
set(ints)

{1, 2, 3, 4}

In [337]:
np.save('data', arr) # 바이너리 형태로 'data.npy' 파일이 저장됨

In [340]:
np.load('data.npy')*100

array([  -3.27051729,  127.490392  ,    1.22844909,  -27.5739961 ,
       -196.38449315, -179.04738904,   63.17928958, -144.80940193,
        183.82398334,   30.13192468,  210.43793889,  -81.90869042,
         94.79383721, -103.37696177,  153.80922086, -184.20706941,
        -17.70183564,  -11.90592321,   65.10718803,  126.95363458,
       -134.14932958,  -29.33328835,  -24.24589014, -305.69897413,
        191.84030172,  -57.88276943,  184.74462567,   45.37392737,
        -30.24502435,  140.25576867,  121.23543772, -161.34741701,
        -57.39664197,   42.4894094 ,  125.75444663, -106.53425495,
         27.63561726,  168.01345516,  -67.93346587,  -12.96973244,
       -193.09312136,  -60.76377585,  -19.52579767, -207.74029473,
         42.26479917,  200.16142991,  138.59142997, -110.4684716 ,
         67.70976065,   56.01605035,  -81.53683286,  100.49142437,
         36.18008017,  -34.04870936,   46.23869784,  -86.67801794,
         65.32703693, -195.6438352 ,  -12.84740225,  -69.55286

In [341]:
brr = np.arange(10)
brr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [352]:
np.savez('data2',a=arr, b=brr) # 여러개의 배열을 저장하는 방법이며 확장자는 npz임

In [353]:
x = np.load('data2.npz')
x['b'] # dict 데이터 다룰 때와 같이 key값을 통해서 찾아야함

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [361]:
brr.max()
brr.min()
brr.mean()

4.5

In [ ]:
# 판다스에서 데이터 타입은 시계열(series), 표(table)임
# 시계열 -> Series(1차원)
# 표 -> DataFrame(2차원)
# pandas는 시리즈와 ,데이터프레임 클래스를 제공
# 즉 모든 데이터는 시계열 혹은 데이터 분석을 한다고 보면 됨

In [363]:
import pandas as pd # 관례임. 안쓰면 욕?먹는다고 함
# 그만큼 pd.read_csv같은 것도 검색하면 당연하단 듯이 잘 나옴
# 넘파이와 판다스는 다름. 넘파이에는 배열이 있는데 판다스에는 시리즈가 있듯 전혀 다른 것임
# python : list, tuple, dict, set
# numpy : ndim(n-dimensional), array
# pandas : Series, DataFrame
# 서로 다르지만 전부 알아야 판다스를 다룰 수 있음
# Series : numpy 1차원 array와 매우 유사함. 차이점은 series는 index가 있음
# 시리즈 = 데이터 + 인덱스
# DataFrame : numpy 2차원 array와 매우 유사함. 차이점은 dataframe은 index가 있음...
# 데이터프레임 = 데이터(2차원) + 행인덱스 + 열인덱스

In [371]:
lst = [1,2,3]
np.array(lst)
pd.Series(lst)

0    1
1    2
2    3
dtype: int64

In [372]:
s = pd.Series([10,20,30,40])
s

0    10
1    20
2    30
3    40
dtype: int64

In [373]:
s2 = pd.Series([10,20,30,40], index=['월', '화', '수', '목']) # 행 인덱스를 직접 부여함
s2

월    10
화    20
수    30
목    40
dtype: int64

In [400]:
s3 = pd.Series([90,70,60,80], index=['홍길동', '임꺽정', '세종', '인조']) # 몸무게
s3
# 시리즈의 진정한 용도는 시계열 데이터를 위함임(실제 데이터를 보더라도 거의 날짜를 삽입해놓은 경우가 많음)

홍길동    90
임꺽정    70
세종     60
인조     80
dtype: int64

In [379]:
pd.Series(list(range(10,15)))
pd.Series(np.arange(10,15)) # 둘다 됨

0    10
1    11
2    12
3    13
4    14
dtype: int32

In [388]:
s3.astype('int64')

홍길동    90
임꺽정    70
세종     60
인조     80
dtype: int64

In [394]:
s3.index

Index(['홍길동', '임꺽정', '세종', '인조'], dtype='object')

In [391]:
s3.values

array([90, 70, 60, 80], dtype=int64)

In [401]:
s3.index.name='인물'
s3.name='몸무게'

In [404]:
s3

인물
홍길동    90
임꺽정    70
세종     60
인조     80
Name: 몸무게, dtype: int64

In [406]:
s3/10 # numpy처럼 연산 적용이 가능함

인물
홍길동    9.0
임꺽정    7.0
세종     6.0
인조     8.0
Name: 몸무게, dtype: float64

In [410]:
s3['세종']
s3[2] # 과거에 사용했던 방법으로 권장하지는 않지만 세종을 입력했을때와 동일한 결과가 나옴
s3.iloc[2] # s3[2]가 권장되지 않지만 이 방법은 정석인 방법이며 권장됨

60

In [418]:
# s3['임꺽정', '세종']  # 인덱스는 한개밖에 안되므로 아래와 같이 사용해야됨
s3[['임꺽정', '세종']] # numpy에서 했던 것처럼 대괄호로 한번더 묶어서 사용해야됨
s3.iloc[[1,2]]

인물
임꺽정    70
세종     60
Name: 몸무게, dtype: int64

In [419]:
s3[['인조', '세종']] # 순서도 변경이 가능함

인물
인조    80
세종    60
Name: 몸무게, dtype: int64

In [423]:
print(s3>70)
s3[s3>70] # 당연히 boolean 참조도 가능함

인물
홍길동     True
임꺽정    False
세종     False
인조      True
Name: 몸무게, dtype: bool


인물
홍길동    90
인조     80
Name: 몸무게, dtype: int64

In [427]:
# s3에서 데이터 값이 60이상 80이하인 자료를 추출하시오
s3[(80>=s3) & (s3>=60)]

인물
임꺽정    70
세종     60
인조     80
Name: 몸무게, dtype: int64

In [431]:
s3.iloc[1:]
s3['임꺽정':'인조'] # 이런식으로 인덱스명을 지목해서 범위를 줄 수 있음;;

인물
임꺽정    70
세종     60
인조     80
Name: 몸무게, dtype: int64

In [ ]:
# 연습문제

In [510]:
# 1. 동전을 20번 던져 앞면(숫자 1)과 뒷면(숫자 0)이 나오는 실험을 파이썬으로 작성하여 출력해보자(numpy)
import numpy as np
[np.random.randint(0,2) for _ in range(20)]
np.random.randint(0,2,20)

array([0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0])

In [511]:
# 2. 주사위를 10000번 던져서 나오는 숫자의 평균을 구하라.(numpy)
np.mean([np.random.randint(1,7) for _ in range(10000)])
np.mean(np.random.randint(1,7,10000))

3.5032

In [500]:
# 3. 난수로 이루어진 4 x 5 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구한다.(numpy)
rc = np.random.random([4,5])
print(rc)
# 전체의 최댓값
print('전체 최댓값:',rc.max())
# 각 행의 합
print('각행의 합:',rc.sum(axis=1))
# 각 행의 최댓값
print('최댓값:',rc.max(axis=1))
# 각 열의 평균
print('평균값:',rc.mean(axis=0))
# 각 열의 최솟값
print('최솟값:',rc.min(axis=0))


[[0.39454507 0.53788406 0.29449138 0.50623315 0.64353587]
 [0.25418114 0.88466649 0.78887533 0.71322282 0.17991732]
 [0.86945957 0.9762982  0.6588788  0.02818168 0.22843703]
 [0.9130145  0.83647058 0.49057524 0.04876331 0.5010142 ]]
전체 최댓값: 0.9762982045590121
각행의 합: [2.37668954 2.8208631  2.76125528 2.78983783]
최댓값: [0.64353587 0.88466649 0.9762982  0.9130145 ]
평균값: [0.60780007 0.80882983 0.55820519 0.32410024 0.38822611]
최솟값: [0.25418114 0.53788406 0.29449138 0.02818168 0.17991732]


In [466]:
# 4.  다음 데이터를 시리즈 구조로 정의하고 '광주' 도시의 인구를 참조하시오
# 서울-1000, 부산-300, 인천-200, 광주-100
import pandas as pd
pd.Series([1000, 300, 200, 100], index=['서울', '부산','인천','광주'])

서울    1000
부산     300
인천     200
광주     100
dtype: int64

In [469]:
# 5. 다음의 Series를 생성하고 sample 변수에 대입하고 출력하세요
# [출력]
# 가    10
# 나    20
# 다    30
# 라    40
# 마    50
# dtype: int64
sample = pd.Series(np.arange(10,60,10), index=['가','나','다','라','마'],dtype='int64')
sample

가    10
나    20
다    30
라    40
마    50
dtype: int64

In [492]:
# 6. sample중 '나'와 '라' 데이터를 조회하세요
sample[['나','라']]
sample.iloc[[1,3]]

나    20
라    40
dtype: int64

In [474]:
# *기본 코드*
# np.random.seed(20)
# sample2 = pd.Series(np.random.randint(100, 200, size=(15,)))
# sample2

# 7. sample2 중 160 이하인 데이터만 필터하세요
np.random.seed(20)
sample2 = pd.Series(np.random.randint(100, 200, size=(15,)))
sample2[sample2<=160]

2     115
4     128
6     109
7     120
9     122
11    134
13    140
dtype: int32

In [475]:
# 8. sample2 중 130 이상 170 이하인 데이터만 필터하세요
sample2[(sample2 >= 130) & (sample2 <= 170)]

11    134
13    140
dtype: int32

In [493]:
# 9.다음과 같은 Series를 생성해 주세요
# [출력]
# 가     apple
# 나       NaN
# 다    banana
# 라      kiwi
# 마    gubong
# dtype: object
# NaN
pd.Series(['apple', np.NaN, 'banana', 'kiwi', 'gubong'], index=['가','나','다','라','마'])

가     apple
나       NaN
다    banana
라      kiwi
마    gubong
dtype: object

In [490]:
# 10. 숫자로 이루어진 리스트에서 사용자가 입력한 숫자를 검색하는 모듈을 다음 요건에 따라 만들어 보자
#  검색 모듈은 선형 검색 알고리즘을 이용하자
#  리스트는 1부터 20까지의 정수 중에서 난수 10개를 이용한다.
#  검색에 성공하면 해당 정수의 인덱스를 출력하고, 검색 결과가 없다면 -1을 출력하자

lst = [np.random.randint(1,21) for _ in range(10)]
# print(lst)
try:
    print(lst.index(10))
except:
    print(-1)

[16, 19, 15, 20, 11, 11, 2, 19, 18, 9]
-1


-1
