In [2]:
pip install torchtext

   ---------------------------------------- 0.0/1.1 MB ? eta -:--:--
   ---------------------------------------- 1.1/1.1 MB 15.3 MB/s eta 0:00:00

   ---------------------------------------- 2/2 [torchtext]

Note: you may need to restart the kernel to use updated packages.


In [3]:
pip list

Package                  Version
------------------------ ------------
absl-py                  2.3.1
anaconda-anon-usage      0.7.1
annotated-types          0.6.0
archspec                 0.2.3
asttokens                3.0.0
astunparse               1.6.3
beautifulsoup4           4.13.4
boltons                  25.0.0
brotlicffi               1.0.9.2
certifi                  2025.7.14
cffi                     1.17.1
charset-normalizer       3.3.2
colorama                 0.4.6
comm                     0.2.3
conda                    25.5.1
conda-anaconda-telemetry 0.2.0
conda-anaconda-tos       0.2.1
conda-content-trust      0.2.0
conda-libmamba-solver    25.4.0
conda-package-handling   2.4.0
conda_package_streaming  0.12.0
contourpy                1.3.3
cryptography             45.0.3
cycler                   0.12.1
debugpy                  1.8.15
decorator                5.2.1
distro                   1.9.0
executing                2.2.0
filelock                 3.13.1
flatbuffers   

In [7]:
import torch
torch.cuda.is_available()
device = 'cuda'

In [11]:
w = torch.tensor(1.0, requires_grad=True)
x = 3

In [14]:
a = w*x
out = a ** 2
out # 역전파가 가능하도록 grad_fn이 생성된 것을 확인할 수 있음

tensor(9., grad_fn=<PowBackward0>)

In [16]:
print(w.grad)

None


In [19]:
x = 3
w = torch.tensor(1.0, requires_grad=True)
z = w*x
out = z ** 2
out.backward()
print('out을 w로 미분한 값', w.grad)

out을 w로 미분한 값 tensor(18.)


# tensor

In [23]:
import numpy as np
data = np.array([[1,2,3],[4,5,6],[7,8,9]])
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]]) # 앞으로는 가급적 텐서 형태로 바꿔서 쓰자
print(data, x)

[[1 2 3]
 [4 5 6]
 [7 8 9]] tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [24]:
x.shape

torch.Size([3, 3])

In [25]:
x.size()

torch.Size([3, 3])

In [26]:
x.ndim

2

In [27]:
x.ndimension()

2

In [28]:
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [32]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
x=torch.unsqueeze(x, 0) # 차원 확장
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [33]:
x=torch.squeeze(x) # 차원 축소
x, x.shape

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 torch.Size([3, 3]))

In [35]:
x.view(9)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
x+1 # 브로드캐스팅 연산

tensor([[ 2,  3,  4],
        [ 5,  6,  7],
        [ 8,  9, 10]])

In [38]:
np.array([1,2,3]).shape # 고정된 축

(3,)

In [44]:
w = torch.randn(5,3, dtype=torch.float) # (고차원, 저차원) 타입은 항상 지정하는 것을 권장함
w
# 메트릭스로 표현하는데 연립방정식으로 표현하기 쉽기 때문임
x = torch.tensor([[1.,2.],[3.,4.],[5.,6.]])
w.shape, x.shape

(torch.Size([5, 3]), torch.Size([3, 2]))

In [ ]:
# wx => (5,3) (3,)
# xw => (,5) (5,3) 
w.shape

torch.Size([5, 3])

In [45]:
b = torch.randn(5,2, dtype=torch.float)
b.shape

torch.Size([5, 2])

In [48]:
w@x # torch.mm(w, x)

tensor([[-1.1839, -0.7554],
        [ 8.3648, 10.2328],
        [ 8.7380, 11.5817],
        [ 1.7955,  2.7585],
        [-0.9579, -2.8464]])

In [49]:
torch.mm(w,x).shape

torch.Size([5, 2])

In [50]:
wx = torch.mm(w,x)
z = wx + b
z

tensor([[-0.8232,  0.9679],
        [10.0458,  9.0848],
        [ 9.0261, 10.5289],
        [ 2.0334,  4.4117],
        [-0.2175, -3.6858]])

In [ ]:
import numpy as np
import torch
from sklearn.datasets import make_blobs
n_dim = 2
tr_x, tr_y = make_blobs(n_samples=80, n_features=2, centers=[[1,1], [-1,-1], [1,-1], [-1,1]], shuffle=True, cluster_std=.3)
tt_x, tt_y = make_blobs(n_samples=20, n_features=2, centers=[[1,1], [-1,-1], [1,-1], [-1,1]], shuffle=True, cluster_std=.3)

In [ ]:
# 임시 데이터 준비 과정
ck_y = tr_y.copy()
def label_map(y, from_, n):
    ck_y = y.copy()
    for i in from_:
        ck_y[y==i] = n
    return ck_y
tr_y=label_map(tr_y, [0,1], 0)
tr_y=label_map(tr_y, [2,3], 1)
tt_y=label_map(tt_y, [2,3], 1)
tt_y=label_map(tt_y, [2,3], 1)

array([2, 3, 3, 3, 0, 3, 3, 2, 0, 0, 3, 0, 0, 3, 1, 1, 0, 2, 0, 2, 2, 3,
       0, 2, 1, 3, 2, 2, 3, 2, 3, 1, 1, 1, 0, 2, 0, 0, 2, 1, 1, 1, 1, 2,
       0, 3, 0, 3, 1, 2, 0, 1, 2, 2, 1, 3, 3, 3, 1, 3, 1, 1, 0, 2, 2, 0,
       1, 0, 3, 1, 0, 0, 2, 3, 0, 1, 1, 2, 3, 2])