In [8]:
import torch
torch.cuda.is_available()

True

In [9]:
t = torch.tensor(10.2, dtype=torch.double)
tensor_1 = torch.arange(0,1000,0.001)

In [10]:
tensor_1

tensor([0.0000e+00, 1.0000e-03, 2.0000e-03,  ..., 1.0000e+03, 1.0000e+03,
        1.0000e+03])

In [11]:
t

tensor(10.2000, dtype=torch.float64)

In [12]:
t = t.int()
t

tensor(10, dtype=torch.int32)

In [13]:
empty_t = torch.empty(2,4)
ones_t = torch.ones(2,4)
rand_t = torch.rand(3,3)
randn_t = torch.randn(30)

In [14]:
empty_t

tensor([[-1.0079e+00,  1.3733e-42,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [15]:
ones_t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [16]:
rand_t

tensor([[0.6789, 0.9415, 0.6836],
        [0.7153, 0.9215, 0.5848],
        [0.6474, 0.7931, 0.5578]])

In [17]:
randn_t

tensor([ 0.9504,  0.7974, -0.1858, -0.7573, -1.0448,  0.1064,  0.3312,  0.2701,
         1.4459,  0.3014, -0.4370,  0.5355, -0.5035, -0.5849, -0.8012,  0.1734,
        -0.0243,  1.4426,  1.1438, -1.2862,  0.3698,  1.2435, -1.0852,  0.6231,
        -0.8649,  1.1518,  1.8435,  1.3425,  0.6149, -1.6694])

In [19]:
torch.mean(rand_t), torch.std(rand_t)

(tensor(0.7249), tensor(0.1359))

In [21]:
a = torch.ones(2,3)
b = torch.ones(2,3) * 2
c = a + b # 텐서 덧셈
d = torch.mm(a, b.T) # 행렬 곱

In [22]:
a, b

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[2., 2., 2.],
         [2., 2., 2.]]))

In [23]:
c

tensor([[3., 3., 3.],
        [3., 3., 3.]])

In [25]:
a, b.T

(tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[2., 2.],
         [2., 2.],
         [2., 2.]]))

In [26]:
d  
# [[1., 1., 1.],  * [[2., 2.],
#  [1., 1., 1.]]     [2., 2.],
#                    [2., 2.]]

tensor([[6., 6.],
        [6., 6.]])